### ISSUE TITLE
Opening in terminal editors fails

### ISSUE THREAD

**Issue by M1dgard** [united-bashers/mkbash#10]
```bash
open() {
	bg 2>/dev/null
	$EDITOR "$scriptname" &
}
```

This does not appear to work.

```
$ mkbash test
Created "test"
Open script? (y/n) y
Received SIGHUP or SIGTERM

```

Edit: This is because the editor is opened as a bg job, which is necessary to prevent editors with a GUI from blocking mkbash.

**Comment by Thhollev** [comment]
open() {
    bg 2>/dev/null
    $EDITOR "$scriptname"&
}

**Comment by M1dgard** [comment]
That fixes nothing ... It seems that you want to cater for GUI editors like gedit by placing mkbash in the background and opening the editor in a background process as well. `bg` fails and you ignore the error, but the call effectively has no effect. (I.e. your function would do the same if it were written as just `open() { $EDITOR "$scriptname" & }`).

For graphical editors, this works quite well (apart from the stdout and stderr of the program, that gets put inside mkbash's output). For terminal-based editors like nano however, it doesn't.

**Comment by Thhollev** [comment]
better ? :stuck_out_tongue:

**Comment by M1dgard** [comment]
Still
